import "../globals.css";
import Mainnav from "./components/mainnav";

export const metadata = {
  title: "dashboard",
  description: "Generated by Next + Sanity",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="w-full  gap-8 bg-black text-white">
        <header>
          <Mainnav />
        </header>
        <main className="w-full  grid place-items-center py-8  ">
          <div className="flex laptop:w-[1200px] items-start gap-8 ">
            {/* <Sidenav /> */}
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
