import "../globals.css";
import Mainnav from "./components/mainnav";
import Sidenav from "./components/sidenav";

export const metadata = {
  title: "dashboard",
  description: "Generated by Next + Sanity",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="w-full h-[100vh] overflow-hidden grid bg-black text-white">
        <header>
          <Mainnav />
        </header>
        <main className="w-full h-full grid place-items-center">
          <div className="h-full flex laptop:w-[1200px] gap-8">
            {/* <Sidenav /> */}
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
