"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./Landingpage/Components/Navbar";
import { useState } from "react";
import Footer from "./Landingpage/Components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const [navigationHeight, setNavigationHeight] = useState<string>("");

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
