"use client";
import "../globals.css";
import { Inter } from "next/font/google";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="w-full grid place-items-center shadow-bs fixed z-[99] bg-white ">
          <Navbar />
        </header>
        <div className=" relative oveflow-hidden pb-0"> {children}</div>
        <footer className="w-full grid place-items-center p-4 bg-gray-200 ">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
