"use client";
import "../globals.css";
import { Inter } from "next/font/google";
import Navbar from "./Components/Navbar";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="w-full grid place-items-center shadow-bs fixed z-[99] ">
          <Navbar />
        </header>
        <div className="top-[72px] relative"> {children}</div>
        <footer></footer>
      </body>
    </html>
  );
}
